Update the app to use IndexedDB to save Sequence data
web4bio/webgen pull request #355
Opened 2021-11-05 16:59 UTC by ericr491

* Use of LokiJS library

2021-11-08 00:35 UTC, kaczmarj requested changes
great changes. thanks. a few comments

- instead of functions being named `loki___`, how about we put the functions inside a namespace named `cache`? i say this because when someone else reads loki, it might not mean anything to them. and loki in my opinion is just an implementation detail. what we are really concerned with here is caching. so how about a namespace that contains the database variable and the related methods. this would also work towards refactoring the app towards a set of modules (#202). this could be our caching module.

```javascript
const cache = {
  db: null,
  initialize() {},
  get(key) { 
    // get something from the database
  },
  set(value) {
    // set a value in the database
  },
};
```

in methods that need the `db` variable, we can use `this.db`. this makes `db` no longer a global variable. instead, `cache` would be a variable, and we can use this in intuitive ways, like `cache.set()` and `cache.get()`.

2021-11-08 00:35 UTC, kaczmarj commented on main/html/index.html
> +        <script src="../js/libraries/loki-indexed-adapter.min.js"></script>
what's the purpose of `loki-indexed-adapter.min.js`?

2021-11-08 00:35 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +}
this fetch function is out of the scope of the caching utility. what i think we should do instead is use caching in the higher-level fetchers, like in https://github.com/web4bio/webgen/blob/0dca517e62d5a6c9b03a1070e7e10c65b1a598aa/main/js/dataAcquisition/fetch.js#L278-L305

i say this because i think the lower-level fetching function should be separate from caching. but it would make sense for high-level fetch functions to first try to retrieve the data from the cache. and if the cache key is not found, then the data will be fetched from the web.

2021-11-08 00:35 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +lokiRefetch = async (url) => {
what is the difference between this function and `lokiRefetch`?

2021-11-08 00:35 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +lokiTest = () => {
what is the purpose of this function?

2021-11-08 00:35 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +    let users = db.getCollection('rnaSeq')
a generic function like `lokiSet` should not use `rnaSeq` as the collection, because this suggests that the function should only be used for rnaSeq data (if that's the case, the function name should be changed). instead, how about we make the collection name a function parameter.

2021-11-08 00:35 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +            [key]: typeof data === 'string' ? JSON.parse(data) : data
do the `.update` / `,insert` methods expect a javascript object (ie not a JSON-serialized string)? if so, we need to document this, and functions that write data to the cache should not serialize objects to JSON.

in other words, if the database does not expect JSON strings, we should not be doing this

```javascript
lokiSet('clinicalData', JSON.stringify(clinicalData))
```

2021-11-08 00:35 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +    let users = db.getCollection('rnaSeq')
similar to my comment on `lokiSet`, we should not be using only a collection `rnaSeq`. this should probably be a function parameter.

2021-11-10 23:56 UTC, ericr491 commented on main/js/dataAcquisition/lokiFetch.js
> +}
From what I understand, you want to delegate the responsibility of saving/reading to the cache to the function fetchmRNASeq and other similar functions?

2021-11-10 23:58 UTC, ericr491 commented on main/js/dataAcquisition/lokiFetch.js
> +            [key]: typeof data === 'string' ? JSON.parse(data) : data
It is able to store objects as well as serialized strings.

2021-11-11 12:04 UTC, kaczmarj commented on main/js/dataAcquisition/lokiFetch.js
> +}
yes - but those higher-level functions would use the functioned defined here by you to read/write to the cache. what do you think about that?

2021-11-11 12:07 UTC, kaczmarj commented
@ericr491 - i really like your current implementation with the `cache` object!

2021-11-11 19:46 UTC, ericr491 commented on main/js/dataAcquisition/lokiFetch.js
> +}
Sounds good to me.

2021-11-11 19:46 UTC, ericr491 commented on main/html/index.html
> +        <script src="../js/libraries/loki-indexed-adapter.min.js"></script>
It specifies the Loki object to connect (make use) of IndexedDB instead of localStorage.

2021-11-12 14:24 UTC, kaczmarj commented
@ericr491 - the changes look good to me. just two small comments. i would remove the big commented block of code at the bottom of the database file. i put the commented code below so we can use it as a reference for later.

<details>
<summary>lokiFetch, lokiRefetch, lokiTest</summary>

```javascript
lokiFetch = async (url) => {
  if (db) {
    const queries = db.getCollection("queries");
    if (queries) {
      const apiCall = await queries.findOne({
        url
      });
      if (apiCall && !(Math.floor(new Date().getTime() / 1000.0) - apiCall.dt >= 1209600)) {
        return apiCall.data;
      } else {
        return lokiRefetch(url);
      }
    }
  } else {
    console.warn("Loki library is not loaded in properly, no caching available.");
    try {
      const response = await fetch(url);
      if (response.ok)
        return await response.json();
      else if (fetchedClinicalData.status === 404) {
        return Promise.reject({});
      } else {
        throw new Error("Failed to fetch.");
      }
    } catch (e) {
      console.error(e);
      return Promise.reject({});
    }
  }
};

lokiRefetch = async (url) => {
  const queries = db.getCollection("queries");
  try {
    const result = await fetch(url);
    if (result.ok) {
      const json = await result.json();
      queries.insert({
        url,
        data: json,
        dt: Math.floor(new Date().getTime() / 1000.0)
      });
      db.saveDatabase((err) => {
        if (err) {
          console.error(err);
        }
      });
      return json;
    } else if (result.status === 404) {
      return Promise.reject({}); // obtain result via await
    } else {
      throw new Error("Failed to fetch.");
    }
  } catch (e) {
    console.error(e);
    return Promise.reject({});
  }
};

lokiTest = () => {
  const queries = db.getCollection("queries");
  let queriesCount = queries.count();

  queries.insert({ url: "localhost", data: [{ asdf: "asdf" }], dt: Math.floor(new Date().getTime() / 1000.0) });
  queriesCount = queries.count();

  console.log(`old number of entries in database : ${  queriesCount}`);
  db.saveDatabase((err) => {
    if (err) {
      console.error(err);
    } else {
      console.log("Saved");
    }
  });
};
```

</details>

also let's resolve the conflicts and update the use of the `cache` object in the code base. then this will be good to merge on my end

2021-11-12 16:29 UTC, kaczmarj approved these changes

2021-11-12 16:32 UTC, kaczmarj commented
@ericr491 - did you want to make additional changes or is this ready to merge?

2021-11-12 17:23 UTC, merged