Plots jsdocs
web4bio/webgen pull request #369
Opened 2021-12-03 16:36 UTC by amaraim22

2021-12-03 16:36 UTC, amaraim22 commented
new pr: for createHeatmap.js, there's only one large function. we were talking about moving functions out if some functions were used by the code in createViolinPlot.js. there's also the benefit of moving helpers functions out of the main large function for better documentation. I just made this pr if anyone has any opinions/feedbacks on anything written. there will also be more commits later on added to this as well.

2021-12-03 21:28 UTC, kaczmarj requested changes
looks great @amaraim22 - i just have two minor requested changes.

2021-12-03 21:28 UTC, kaczmarj commented on main/js/plots/createPieCharts.js
>  let displayNumberBarcodesAtIntersection = async function () {
if this is unused, we should remove the function. it will still exist in the git history of the project, so others can look back to it if they're interested

2021-12-03 21:28 UTC, kaczmarj commented on main/js/plots/createViolinPlot.js
> +            console.log(density);                                        // Implement kernel density estimation
can you remove this console.log ?

2021-12-08 20:34 UTC, kaczmarj commented on main/js/plots/createViolinPlot.js
>  function wrap(text, width)
we can remove this if it is unused

2021-12-08 20:35 UTC, kaczmarj commented
@amaraim22 - these changes look great to me. anything else you wanted to do in this pr? or is it ready to go?

2021-12-09 03:05 UTC, amaraim22 commented
@kaczmarj it is ready to go but there might still be more to be documented. if that's the case then i'll just make a new pr?

2021-12-09 03:53 UTC, kaczmarj commented
> @kaczmarj it is ready to go but there might still be more to be documented. if that's the case then i'll just make a new pr?

yeah i think that's a good idea. it will be good to merge in these changes, and future changes can come in other prs. before we merge, could you remove the unused function `wrap` ? then it's good on my end

2021-12-09 13:03 UTC, kaczmarj approved these changes

2021-12-09 13:03 UTC, merged